package ru.dyatel.inuyama

const val ITEM_TYPE_NETWORK = 1
const val ITEM_TYPE_DIRECTORY = 2
const val ITEM_TYPE_RUTRACKER_WATCH = 3
const val ITEM_TYPE_MODULE_STATE = 4
const val ITEM_TYPE_NYAA_WATCH = 5
const val ITEM_TYPE_DASHBOARD_UPDATE = 6
const val ITEM_TYPE_RURANOBE_PROJECT = 7
const val ITEM_TYPE_RURANOBE_VOLUME = 8

const val NOTIFICATION_CHANNEL_UPDATES = "updates"

const val NOTIFICATION_ID_UPDATE = 1

const val WORK_NAME_OVERSEER = "${BuildConfig.APPLICATION_ID}:overseer"

const val DASHBOARD_UPDATE_COUNT = 8

const val RURANOBE_COVER_ASPECT_RATIO = 240.0 / 343
const val RURANOBE_COVER_SIZE = 6